#!/usr/bin/env bun
// Builds the React dashboard client via Bun and inlines the JS + CSS into
// src/dashboard/bundle.ts so the daemon binary can serve them as a single shell.

import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = new URL("..", import.meta.url).pathname;
const ENTRY = join(ROOT, "src/dashboard/client/index.tsx");
const OUT_DIR = join(ROOT, ".dashboard-build");
const BUNDLE_OUT = join(ROOT, "src/dashboard/bundle.ts");

if (existsSync(OUT_DIR)) rmSync(OUT_DIR, { recursive: true, force: true });
mkdirSync(OUT_DIR, { recursive: true });

const result = await Bun.build({
  entrypoints: [ENTRY],
  outdir: OUT_DIR,
  target: "browser",
  minify: true,
  // React 18 needs NODE_ENV inlined so it doesn't ship the dev-mode bundle.
  define: { "process.env.NODE_ENV": '"production"' },
  // No sourcemap in the shipped bundle — we inline it into a TS string,
  // and sourcemaps would bloat the binary.
});

if (!result.success) {
  for (const msg of result.logs) console.error(msg);
  throw new Error("bun build failed");
}

const files = readdirSync(OUT_DIR);
const jsFile = files.find((f) => f.endsWith(".js"));
const cssFile = files.find((f) => f.endsWith(".css"));
if (!jsFile) throw new Error("no js output produced");

// Escape HTML-significant sequences so the inline <script> and <style> blocks
// can't be closed prematurely by content in the bundle. (e.g. React's bundle
// contains a literal "<script></script>" string for a DOM feature-detect.)
function escapeForInlineHtml(s: string): string {
  return s.replace(/<\/(script|style)/gi, "<\\/$1");
}

const js = escapeForInlineHtml(readFileSync(join(OUT_DIR, jsFile), "utf-8"));
const css = cssFile ? escapeForInlineHtml(readFileSync(join(OUT_DIR, cssFile), "utf-8")) : "";

const jsBytes = Buffer.byteLength(js, "utf-8");
const cssBytes = Buffer.byteLength(css, "utf-8");

// JSON.stringify produces a safely-escaped JS string literal.
const ts = `// Auto-generated by scripts/bundle-dashboard.ts — do not edit by hand.
// Regenerate with: bun run build:dashboard
/* eslint-disable */
export const DASHBOARD_JS = ${JSON.stringify(js)};
export const DASHBOARD_CSS = ${JSON.stringify(css)};
`;

writeFileSync(BUNDLE_OUT, ts);
rmSync(OUT_DIR, { recursive: true, force: true });

console.log(`Bundled dashboard: ${jsBytes} B js + ${cssBytes} B css → ${BUNDLE_OUT}`);
